# Generated by Django 5.1.4 on 2025-01-21 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rating_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students_month',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_students_month', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='students_year',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_students_year', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=1, upload_to='images/subjects'),
            preserve_default=False,
        ),
    ]
