# Generated by Django 5.1.4 on 2025-01-27 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_month',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_year',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
